import { leaseSchedule, maintenanceSchedule } from "./catalog";
import type { CategoryId, Robot, Spec, StockByLocation } from "./types";

/**
 * Seed catalogue. This is written to data/rims.json the first time the app
 * starts and is never read again — after that the JSON file is the record and
 * every change goes through a server action.
 *
 * Beetle's figures are the published ones. The rest carry manufacturer
 * specifications for the same model; check them against the current datasheet
 * before quoting.
 */

interface CoreSpecs {
  dimensions?: string;
  weight?: string;
  speed?: string;
  battery?: string;
  runtime?: string;
  charge?: string;
  navigation?: string;
  sensors?: string;
  connectivity?: string;
  noise?: string;
  ingress?: string;
  climb?: string;
}

interface SeedRobot {
  slug: string;
  name: string;
  modelId: string;
  category: CategoryId;
  tagline: string;
  description: string;
  buyOff: number;
  reorderPoint?: number;
  reserved?: number;
  /** [warehouse code, on hand, demo] */
  stock: [string, number, number][];
  core: CoreSpecs;
  /** Model-specific rows, appended after the common ones. */
  extra?: [string, string][];
}

const CORE_ORDER: [keyof CoreSpecs, string][] = [
  ["dimensions", "Dimensions (L × W × H)"],
  ["weight", "Net weight"],
  ["speed", "Max. moving speed"],
  ["climb", "Gradeability"],
  ["battery", "Battery capacity"],
  ["runtime", "Working time"],
  ["charge", "Charging time"],
  ["navigation", "Navigation"],
  ["sensors", "Sensor system"],
  ["connectivity", "Connectivity"],
  ["noise", "Noise level"],
  ["ingress", "Ingress protection"],
];

const SEED: SeedRobot[] = [
  /* ------------------------------- cleaning ------------------------------ */
  {
    slug: "beetle",
    name: "Beetle",
    modelId: "BEETLE",
    category: "cleaning",
    tagline: "Compact industrial sweeper",
    description:
      "Sweeps and vacuums in a single pass, sized to turn inside a standard factory aisle. The 45-litre bin holds a full shift of debris, and side brushes pull dirt out of wall edges the main brush cannot reach.",
    buyOff: 450_000,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "960 × 650 × 680 mm",
      weight: "112 kg",
      speed: "1.4 m/s (3.1 mph)",
      climb: "4.6° (8%)",
      battery: "60 Ah",
      runtime: "> 4 hours",
      charge: "2 hours",
      navigation: "SLAM, auto route planning",
      sensors: "3D LiDAR, RGB camera, RGB-D camera",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
    },
    extra: [
      ["Cleaning width", "750 mm (29.5 inches) with side brushes"],
      ["Max. cleaning efficiency", "3,780 m²/h (theoretical)"],
      ["Max. air flow volume", "1,320 m³/h"],
      ["Trash bin capacity", "45 litres"],
      ["Edge cleaning capability", "0 mm (0 inches)"],
      ["Min. return distance", "1,200 mm"],
    ],
  },
  {
    slug: "cleaning-robot-c3",
    name: "Cleaning Robot C3",
    modelId: "C3",
    category: "cleaning",
    tagline: "Entry-level floor scrubber",
    description:
      "The smallest scrubber in the range, built for shops, clinics and offices under 2,000 m². One operator can lift the tanks out for cleaning without tools.",
    buyOff: 320_000,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "700 × 520 × 980 mm",
      weight: "78 kg",
      speed: "1.0 m/s",
      climb: "5° (9%)",
      battery: "24 V / 40 Ah lithium",
      runtime: "3 hours",
      charge: "2.5 hours",
      navigation: "2D LiDAR SLAM",
      sensors: "2D LiDAR, depth camera, ultrasonic array, bumper",
      connectivity: "Wi-Fi 2.4/5 GHz",
      noise: "≤ 62 dB(A)",
    },
    extra: [
      ["Cleaning width", "500 mm"],
      ["Clean water tank", "15 litres"],
      ["Recovery tank", "17 litres"],
      ["Cleaning efficiency", "1,800 m²/h (theoretical)"],
      ["Brush pressure", "18 kg"],
    ],
  },
  {
    slug: "cleaning-robot-c30",
    name: "Cleaning Robot C30",
    modelId: "C30",
    category: "cleaning",
    tagline: "Mid-size scrub and dry unit",
    description:
      "Scrubs and dries in one direction of travel, so a corridor is walkable immediately behind it. Sized for hotel lobbies, hospital wings and mid-size retail.",
    buyOff: 368_000,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "830 × 600 × 1,050 mm",
      weight: "96 kg",
      speed: "1.2 m/s",
      climb: "6° (10%)",
      battery: "24 V / 60 Ah lithium",
      runtime: "4 hours",
      charge: "2.5 hours",
      navigation: "3D LiDAR SLAM, multi-floor mapping",
      sensors: "3D LiDAR, RGB-D camera, ultrasonic array, drop sensors",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 65 dB(A)",
    },
    extra: [
      ["Cleaning width", "600 mm"],
      ["Squeegee width", "760 mm"],
      ["Clean water tank", "25 litres"],
      ["Recovery tank", "28 litres"],
      ["Cleaning efficiency", "2,600 m²/h (theoretical)"],
    ],
  },
  {
    slug: "cleaning-robot-c40",
    name: "Cleaning Robot C40",
    modelId: "C40",
    category: "cleaning",
    tagline: "High-throughput scrubber",
    description:
      "The largest of the C series, with a 40-litre solution tank that clears a shopping centre concourse without a refill stop. Docks and refills itself where a water station is installed.",
    buyOff: 450_000,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "920 × 660 × 1,100 mm",
      weight: "118 kg",
      speed: "1.2 m/s",
      climb: "6° (10%)",
      battery: "24 V / 80 Ah lithium",
      runtime: "5 hours",
      charge: "3 hours",
      navigation: "3D LiDAR SLAM, multi-floor mapping, lift integration",
      sensors: "3D LiDAR, RGB-D camera, ultrasonic array, drop sensors",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 67 dB(A)",
    },
    extra: [
      ["Cleaning width", "700 mm"],
      ["Squeegee width", "880 mm"],
      ["Clean water tank", "40 litres"],
      ["Recovery tank", "45 litres"],
      ["Cleaning efficiency", "3,200 m²/h (theoretical)"],
      ["Auto refill / drain", "Supported with dock station"],
    ],
  },
  {
    slug: "scrubber-50-pro-disc",
    name: "Scrubber 50 Pro (Disc)",
    modelId: "SCR50P-D",
    category: "cleaning",
    tagline: "Commercial scrubber, disc head",
    description:
      "Disc head configuration, for smooth sealed floors such as polished concrete, vinyl and terrazzo. Puts more pressure through a smaller contact patch, which lifts scuffing better than a roller.",
    buyOff: 850_000,
    stock: [
      ["BKK-WH01", 2, 0],
      ["CNX-WH02", 1, 0],
    ],
    core: {
      dimensions: "1,180 × 720 × 1,220 mm",
      weight: "165 kg",
      speed: "1.4 m/s",
      climb: "8° (14%)",
      battery: "36 V / 100 Ah lithium",
      runtime: "6 hours",
      charge: "3 hours",
      navigation: "3D LiDAR SLAM, lift and door integration",
      sensors: "3D LiDAR, stereo camera, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 68 dB(A)",
    },
    extra: [
      ["Head type", "Twin disc"],
      ["Cleaning width", "510 mm"],
      ["Squeegee width", "790 mm"],
      ["Brush pressure", "35 kg"],
      ["Clean water tank", "50 litres"],
      ["Recovery tank", "55 litres"],
      ["Cleaning efficiency", "3,500 m²/h (theoretical)"],
    ],
  },
  {
    slug: "scrubber-50-pro-roller",
    name: "Scrubber 50 Pro (Roller)",
    modelId: "SCR50P-R",
    category: "cleaning",
    tagline: "Commercial scrubber, roller head",
    description:
      "Roller head configuration, for textured and non-slip floors where a disc rides over the grain. Sweeps loose debris into an integrated hopper ahead of the wash, so the floor needs no pre-sweep.",
    buyOff: 850_000,
    reserved: 2,
    stock: [
      ["BKK-WH01", 7, 0],
      ["CNX-WH02", 3, 0],
    ],
    core: {
      dimensions: "1,180 × 720 × 1,220 mm",
      weight: "172 kg",
      speed: "1.4 m/s",
      climb: "8° (14%)",
      battery: "36 V / 100 Ah lithium",
      runtime: "6 hours",
      charge: "3 hours",
      navigation: "3D LiDAR SLAM, lift and door integration",
      sensors: "3D LiDAR, stereo camera, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 68 dB(A)",
    },
    extra: [
      ["Head type", "Counter-rotating roller"],
      ["Cleaning width", "530 mm"],
      ["Squeegee width", "790 mm"],
      ["Debris hopper", "6 litres"],
      ["Clean water tank", "50 litres"],
      ["Recovery tank", "55 litres"],
      ["Cleaning efficiency", "3,700 m²/h (theoretical)"],
    ],
  },
  {
    slug: "scrubber-75",
    name: "Scrubber 75",
    modelId: "SCR75",
    category: "cleaning",
    tagline: "Ride-on class scrubber",
    description:
      "The largest floor machine RaasPal supplies, for warehouses, airports and exhibition halls. Covers roughly the area of two Scrubber 50 units per shift and carries a 75-litre tank.",
    buyOff: 1_300_000,
    reorderPoint: 3,
    stock: [
      ["BKK-WH01", 3, 2],
      ["CNX-WH02", 1, 0],
    ],
    core: {
      dimensions: "1,420 × 880 × 1,320 mm",
      weight: "285 kg",
      speed: "1.6 m/s",
      climb: "10° (17%)",
      battery: "48 V / 150 Ah lithium",
      runtime: "8 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, GNSS-assisted outdoor mode",
      sensors: "3D LiDAR ×2, stereo camera, ultrasonic array, safety bumper",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 70 dB(A)",
      ingress: "IPX4",
    },
    extra: [
      ["Head type", "Twin disc, floating"],
      ["Cleaning width", "750 mm"],
      ["Squeegee width", "1,020 mm"],
      ["Brush pressure", "55 kg"],
      ["Clean water tank", "75 litres"],
      ["Recovery tank", "85 litres"],
      ["Cleaning efficiency", "5,400 m²/h (theoretical)"],
    ],
  },
  {
    slug: "ecobot-scrubber-50",
    name: "EcoBot Scrubber 50",
    modelId: "ECO-S50",
    category: "cleaning",
    tagline: "Water-saving commercial scrubber",
    description:
      "Recirculates and filters recovered water, cutting fresh water use by roughly half against a conventional scrubber of the same width. Suits sites where filling points are far from the cleaning area.",
    buyOff: 650_000,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "1,100 × 700 × 1,180 mm",
      weight: "148 kg",
      speed: "1.2 m/s",
      climb: "6° (10%)",
      battery: "36 V / 80 Ah lithium",
      runtime: "5 hours",
      charge: "3 hours",
      navigation: "3D LiDAR SLAM",
      sensors: "3D LiDAR, RGB-D camera, ultrasonic array",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 66 dB(A)",
    },
    extra: [
      ["Cleaning width", "500 mm"],
      ["Clean water tank", "45 litres"],
      ["Recovery tank", "50 litres"],
      ["Water recycling", "Three-stage filtration, up to 50% reuse"],
      ["Cleaning efficiency", "3,000 m²/h (theoretical)"],
    ],
  },
  {
    slug: "ecobot-sweep-40",
    name: "EcoBot Sweep 40",
    modelId: "ECO-SW40",
    category: "cleaning",
    tagline: "Dry sweeper for dust and litter",
    description:
      "Dry sweeping only, for car parks, loading bays and platforms where water is not wanted. A HEPA filter keeps fine dust out of the air, so it can run during opening hours.",
    buyOff: 530_000,
    reorderPoint: 8,
    reserved: 3,
    stock: [
      ["BKK-WH01", 9, 6],
      ["CNX-WH02", 3, 3],
      ["PKT-WH03", 2, 1],
    ],
    core: {
      dimensions: "980 × 680 × 1,010 mm",
      weight: "105 kg",
      speed: "1.4 m/s",
      climb: "8° (14%)",
      battery: "24 V / 60 Ah lithium",
      runtime: "5 hours",
      charge: "2.5 hours",
      navigation: "3D LiDAR SLAM",
      sensors: "3D LiDAR, RGB-D camera, ultrasonic array, dust sensor",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 64 dB(A)",
      ingress: "IPX4",
    },
    extra: [
      ["Sweeping width", "780 mm with side brushes"],
      ["Debris hopper", "40 litres"],
      ["Filtration", "HEPA H13"],
      ["Sweeping efficiency", "4,200 m²/h (theoretical)"],
    ],
  },
  {
    slug: "marvel",
    name: "Marvel",
    modelId: "MARVEL",
    category: "cleaning",
    tagline: "Four-in-one commercial cleaner",
    description:
      "Sweeps, scrubs, dusts and vacuums from one chassis by swapping the head module, which replaces up to three single-purpose machines on a mixed-surface site.",
    buyOff: 1_200_000,
    reorderPoint: 3,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "1,240 × 760 × 1,280 mm",
      weight: "215 kg",
      speed: "1.4 m/s",
      climb: "8° (14%)",
      battery: "48 V / 120 Ah lithium",
      runtime: "7 hours",
      charge: "3.5 hours",
      navigation: "3D LiDAR SLAM, lift integration, multi-floor maps",
      sensors: "3D LiDAR ×2, stereo camera, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 69 dB(A)",
    },
    extra: [
      ["Cleaning modes", "Sweep, scrub, dust push, vacuum"],
      ["Cleaning width", "700 mm"],
      ["Clean water tank", "60 litres"],
      ["Recovery tank", "65 litres"],
      ["Debris hopper", "35 litres"],
      ["Cleaning efficiency", "4,000 m²/h (theoretical)"],
    ],
  },
  {
    slug: "mira-cleaning-robot",
    name: "Mira Cleaning Robot",
    modelId: "MIRA",
    category: "cleaning",
    tagline: "Slim scrubber for tight floor plans",
    description:
      "A 460 mm body that fits between fixed shelving and passes through a standard single door. Built for convenience stores, pharmacies and back-of-house corridors.",
    buyOff: 490_000,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "760 × 460 × 990 mm",
      weight: "82 kg",
      speed: "1.0 m/s",
      climb: "5° (9%)",
      battery: "24 V / 50 Ah lithium",
      runtime: "4 hours",
      charge: "2.5 hours",
      navigation: "2D LiDAR SLAM, visual relocalisation",
      sensors: "2D LiDAR, RGB-D camera, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz",
      noise: "≤ 60 dB(A)",
    },
    extra: [
      ["Cleaning width", "420 mm"],
      ["Minimum passage width", "560 mm"],
      ["Clean water tank", "20 litres"],
      ["Recovery tank", "22 litres"],
      ["Cleaning efficiency", "1,500 m²/h (theoretical)"],
    ],
  },
  {
    slug: "mt1",
    name: "MT1",
    modelId: "MT1",
    category: "cleaning",
    tagline: "Outdoor sweeper",
    description:
      "Weather-sealed for pavements, estate roads and open car parks. Handles wet leaves and gravel that would jam an indoor machine, and holds its route on GNSS where the sky is clear.",
    buyOff: 750_000,
    reorderPoint: 3,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "1,560 × 1,020 × 1,340 mm",
      weight: "395 kg",
      speed: "2.2 m/s",
      climb: "15° (27%)",
      battery: "48 V / 200 Ah lithium",
      runtime: "8 hours",
      charge: "5 hours",
      navigation: "GNSS RTK with 3D LiDAR SLAM fallback",
      sensors: "3D LiDAR ×2, RGB camera ×4, ultrasonic array, safety bumper",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 74 dB(A)",
      ingress: "IP54",
    },
    extra: [
      ["Sweeping width", "1,100 mm with twin side brushes"],
      ["Debris hopper", "120 litres"],
      ["Dust suppression", "Water spray, 40-litre tank"],
      ["Sweeping efficiency", "7,800 m²/h (theoretical)"],
      ["Operating temperature", "0 °C to 45 °C"],
    ],
  },
  {
    slug: "omni",
    name: "OMNI",
    modelId: "OMNI",
    category: "cleaning",
    tagline: "All-surface cleaning platform",
    description:
      "Drives sideways and diagonally on omni-directional wheels, so it cleans right up to fixtures without a three-point turn. Best value on sites with dense furniture.",
    buyOff: 1_090_000,
    reorderPoint: 3,
    stock: [
      ["BKK-WH01", 3, 1],
      ["CNX-WH02", 2, 0],
    ],
    core: {
      dimensions: "1,050 × 780 × 1,150 mm",
      weight: "188 kg",
      speed: "1.3 m/s",
      climb: "6° (10%)",
      battery: "48 V / 100 Ah lithium",
      runtime: "6 hours",
      charge: "3 hours",
      navigation: "3D LiDAR SLAM, omni-directional path planning",
      sensors: "3D LiDAR, stereo camera ×2, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 67 dB(A)",
    },
    extra: [
      ["Drive type", "Four-wheel omni-directional (mecanum)"],
      ["Cleaning width", "680 mm"],
      ["Edge clearance", "25 mm from fixtures"],
      ["Clean water tank", "55 litres"],
      ["Recovery tank", "60 litres"],
      ["Cleaning efficiency", "3,400 m²/h (theoretical)"],
    ],
  },
  {
    slug: "phantas-all-in-one",
    name: "PHANTAS: All in One",
    modelId: "PHANTAS-AIO",
    category: "cleaning",
    tagline: "Compact four-mode cleaner",
    description:
      "Scrubs, sweeps, vacuums and dust-pushes from a body small enough for a lift lobby. The volume seller in the cleaning range and the usual answer for multi-tenant offices.",
    buyOff: 380_000,
    reorderPoint: 8,
    reserved: 12,
    stock: [
      ["BKK-WH01", 30, 2],
      ["CNX-WH02", 12, 1],
      ["PKT-WH03", 6, 1],
    ],
    core: {
      dimensions: "700 × 540 × 1,020 mm",
      weight: "88 kg",
      speed: "1.2 m/s",
      climb: "6° (10%)",
      battery: "24 V / 60 Ah lithium",
      runtime: "4.5 hours",
      charge: "2.5 hours",
      navigation: "3D LiDAR SLAM, lift integration, multi-floor maps",
      sensors: "3D LiDAR, RGB-D camera, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 63 dB(A)",
    },
    extra: [
      ["Cleaning modes", "Scrub, sweep, vacuum, dust push"],
      ["Cleaning width", "460 mm"],
      ["Clean water tank", "18 litres"],
      ["Recovery tank", "20 litres"],
      ["Debris hopper", "12 litres"],
      ["Cleaning efficiency", "1,900 m²/h (theoretical)"],
      ["Auto refill / drain", "Supported with dock station"],
    ],
  },

  /* ------------------------------- delivery ------------------------------ */
  {
    slug: "bellabot",
    name: "BellaBot",
    modelId: "BELLA-P1",
    category: "delivery",
    tagline: "Four-tray food runner",
    description:
      "The standard restaurant runner: four trays, 40 kg total, and an expressive face that customers respond to. Carries plates from the pass to the table so waiting staff stay on the floor.",
    buyOff: 180_000,
    reorderPoint: 8,
    reserved: 6,
    stock: [
      ["BKK-WH01", 34, 4],
      ["CNX-WH02", 12, 2],
      ["PKT-WH03", 6, 1],
    ],
    core: {
      dimensions: "565 × 537 × 1,290 mm",
      weight: "55 kg",
      speed: "1.2 m/s",
      climb: "5° (9%)",
      battery: "20 Ah lithium",
      runtime: "12 hours",
      charge: "4.5 hours",
      navigation: "Visual SLAM with marker assistance",
      sensors: "3D obstacle camera, LiDAR, IR pair, collision bumper",
      connectivity: "Wi-Fi 2.4/5 GHz",
      noise: "≤ 50 dB(A)",
    },
    extra: [
      ["Trays", "4"],
      ["Payload per tray", "10 kg"],
      ["Total payload", "40 kg"],
      ["Tray clearance", "160 mm"],
      ["Minimum passage width", "550 mm"],
      ["Display", "10.1-inch expressive face"],
    ],
  },
  {
    slug: "butlerbot-w3",
    name: "ButlerBot W3",
    modelId: "BTL-W3",
    category: "delivery",
    tagline: "Enclosed cabinet delivery robot",
    description:
      "A lockable cabinet on wheels for hotels and hospitals, where what is being carried should not be seen or touched in transit. Calls the lift itself and unlocks only at the destination.",
    buyOff: 430_000,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "560 × 560 × 1,320 mm",
      weight: "72 kg",
      speed: "1.2 m/s",
      climb: "5° (9%)",
      battery: "40 Ah lithium",
      runtime: "14 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, lift and door integration",
      sensors: "3D LiDAR, depth camera ×2, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 52 dB(A)",
    },
    extra: [
      ["Compartments", "3, independently locked"],
      ["Compartment volume", "28 litres each"],
      ["Total payload", "30 kg"],
      ["Access control", "PIN, RFID card, app"],
      ["Lift integration", "Yes, via building API or relay module"],
      ["Display", "10.1-inch touchscreen"],
    ],
  },
  {
    slug: "zara-d150",
    name: "Zara D150",
    modelId: "ZARA-D150",
    category: "delivery",
    tagline: "Open-shelf delivery robot",
    description:
      "Three open shelves for fast pick-and-go rounds where speed matters more than security. Common in staff canteens and hospital ward supply runs.",
    buyOff: 390_000,
    stock: [["BKK-WH01", 2, 0]],
    core: {
      dimensions: "540 × 520 × 1,240 mm",
      weight: "58 kg",
      speed: "1.2 m/s",
      climb: "5° (9%)",
      battery: "30 Ah lithium",
      runtime: "12 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, lift integration",
      sensors: "3D LiDAR, depth camera, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 50 dB(A)",
    },
    extra: [
      ["Shelves", "3, open"],
      ["Payload per shelf", "10 kg"],
      ["Total payload", "30 kg"],
      ["Shelf clearance", "180 mm"],
      ["Display", "10.1-inch touchscreen"],
    ],
  },
  {
    slug: "zara-d300e",
    name: "Zara D300E",
    modelId: "ZARA-D300E",
    category: "delivery",
    tagline: "Extended-range delivery robot",
    description:
      "The D150 platform with a doubled battery and a heavier drivetrain, for sites where a robot cannot leave the round to charge. Runs a full 24-hour rotation on two swappable packs.",
    buyOff: 489_000,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "560 × 540 × 1,260 mm",
      weight: "68 kg",
      speed: "1.4 m/s",
      climb: "6° (10%)",
      battery: "60 Ah lithium, hot-swappable",
      runtime: "20 hours",
      charge: "4.5 hours (or 2-minute pack swap)",
      navigation: "3D LiDAR SLAM, lift and door integration",
      sensors: "3D LiDAR, depth camera ×2, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 52 dB(A)",
    },
    extra: [
      ["Shelves", "3, open"],
      ["Total payload", "40 kg"],
      ["Battery packs supplied", "2"],
      ["Daily coverage", "Up to 24 hours with pack rotation"],
      ["Display", "10.1-inch touchscreen"],
    ],
  },
  {
    slug: "zara-l300",
    name: "Zara L300",
    modelId: "ZARA-L300",
    category: "delivery",
    tagline: "Heavy-load transport cart",
    description:
      "A flat deck that carries 300 kg of linen, stock or parts between departments. Loads at trolley height, so goods do not have to be lifted.",
    buyOff: 500_000,
    stock: [["BKK-WH01", 2, 1]],
    core: {
      dimensions: "1,100 × 700 × 620 mm",
      weight: "135 kg",
      speed: "1.5 m/s",
      climb: "8° (14%)",
      battery: "48 V / 60 Ah lithium",
      runtime: "10 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, lift integration, QR waypoint assist",
      sensors: "3D LiDAR ×2, depth camera, ultrasonic array, safety bumper",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 58 dB(A)",
    },
    extra: [
      ["Deck type", "Flat, non-slip"],
      ["Rated payload", "300 kg"],
      ["Deck height", "620 mm"],
      ["Deck area", "1,000 × 640 mm"],
      ["Towing option", "Cart hitch available"],
    ],
  },
  {
    slug: "zara-l600",
    name: "Zara L600",
    modelId: "ZARA-L600",
    category: "delivery",
    tagline: "Pallet-class transport robot",
    description:
      "Moves 600 kg — a loaded euro pallet — between production, storage and dispatch. Lifts and drops roll cages itself where the site uses compatible frames.",
    buyOff: 600_000,
    reorderPoint: 3,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "1,320 × 850 × 640 mm",
      weight: "210 kg",
      speed: "1.5 m/s",
      climb: "8° (14%)",
      battery: "48 V / 100 Ah lithium",
      runtime: "10 hours",
      charge: "4.5 hours",
      navigation: "3D LiDAR SLAM, reflector-assisted docking",
      sensors: "3D LiDAR ×2, depth camera ×2, ultrasonic array, safety scanner",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 60 dB(A)",
      ingress: "IP44",
    },
    extra: [
      ["Rated payload", "600 kg"],
      ["Lift stroke", "80 mm"],
      ["Deck area", "1,200 × 800 mm"],
      ["Docking accuracy", "± 10 mm"],
      ["Safety rating", "PL d / Cat. 3 safety scanner"],
    ],
  },
  {
    slug: "dinerbot-t10",
    name: "DinerBot T10",
    modelId: "DNR-T10",
    category: "delivery",
    tagline: "Entry-level restaurant runner",
    description:
      "The lowest-cost way to put a runner on a restaurant floor. Three trays, marker-guided navigation, and no site survey needed beyond sticking down the route markers.",
    buyOff: 250_000,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "510 × 510 × 1,180 mm",
      weight: "42 kg",
      speed: "1.0 m/s",
      climb: "4° (7%)",
      battery: "15 Ah lithium",
      runtime: "10 hours",
      charge: "4 hours",
      navigation: "Ceiling marker guidance",
      sensors: "Depth camera, IR pair, collision bumper",
      connectivity: "Wi-Fi 2.4 GHz",
      noise: "≤ 50 dB(A)",
    },
    extra: [
      ["Trays", "3"],
      ["Payload per tray", "10 kg"],
      ["Total payload", "30 kg"],
      ["Site preparation", "Ceiling markers, no floor works"],
      ["Display", "8-inch face"],
    ],
  },
  {
    slug: "flashbot",
    name: "FlashBot",
    modelId: "FLASH-01",
    category: "delivery",
    tagline: "Hotel delivery robot with lift control",
    description:
      "Purpose-built for hotels: calls the lift, rings the room and reports the handover back to the front desk. Its sealed compartment keeps deliveries private end to end.",
    buyOff: 420_000,
    stock: [
      ["BKK-WH01", 5, 0],
      ["CNX-WH02", 2, 0],
    ],
    core: {
      dimensions: "500 × 500 × 1,150 mm",
      weight: "65 kg",
      speed: "1.2 m/s",
      climb: "5° (9%)",
      battery: "40 Ah lithium",
      runtime: "16 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, lift and door integration, multi-floor maps",
      sensors: "3D LiDAR, depth camera ×2, ultrasonic array, anti-drop",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, Bluetooth 5.0",
      noise: "≤ 48 dB(A)",
    },
    extra: [
      ["Compartments", "2, independently locked"],
      ["Compartment volume", "22 litres each"],
      ["Total payload", "20 kg"],
      ["Guest notification", "In-room phone call and SMS"],
      ["Lift integration", "Yes, via building API or relay module"],
      ["Display", "10.1-inch touchscreen"],
    ],
  },
  {
    slug: "gogo",
    name: "GoGo",
    modelId: "GOGO",
    category: "delivery",
    tagline: "Compact tray runner",
    description:
      "A small two-tray runner for cafés and bubble-tea counters where floor space is measured in centimetres. Docks against a wall and takes up less room than a service trolley.",
    buyOff: 210_000,
    reorderPoint: 8,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "430 × 430 × 980 mm",
      weight: "34 kg",
      speed: "1.0 m/s",
      climb: "4° (7%)",
      battery: "15 Ah lithium",
      runtime: "10 hours",
      charge: "3.5 hours",
      navigation: "Visual SLAM with marker assistance",
      sensors: "Depth camera, IR pair, collision bumper",
      connectivity: "Wi-Fi 2.4/5 GHz",
      noise: "≤ 48 dB(A)",
    },
    extra: [
      ["Trays", "2"],
      ["Payload per tray", "8 kg"],
      ["Total payload", "16 kg"],
      ["Docked footprint", "430 × 460 mm"],
      ["Display", "7-inch face"],
    ],
  },
  {
    slug: "id-d1",
    name: "ID-D1",
    modelId: "ID-D1",
    category: "delivery",
    tagline: "Industrial delivery robot",
    description:
      "Built for factory floors rather than lobbies: a sealed chassis, a safety-rated scanner and tolerance for the vibration and dust of a production environment.",
    buyOff: 490_000,
    stock: [["BKK-WH01", 1, 1]],
    core: {
      dimensions: "900 × 620 × 1,100 mm",
      weight: "128 kg",
      speed: "1.5 m/s",
      climb: "8° (14%)",
      battery: "48 V / 60 Ah lithium",
      runtime: "10 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, reflector-assisted docking",
      sensors: "Safety laser scanner, 3D LiDAR, depth camera, safety bumper",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 60 dB(A)",
      ingress: "IP44",
    },
    extra: [
      ["Rated payload", "100 kg"],
      ["Shelves", "2, fixed"],
      ["Safety rating", "PL d / Cat. 3 safety scanner"],
      ["Docking accuracy", "± 15 mm"],
      ["Operating temperature", "0 °C to 45 °C"],
    ],
  },
  {
    slug: "id-d3",
    name: "ID-D3",
    modelId: "ID-D3",
    category: "delivery",
    tagline: "Industrial delivery robot, three-shelf",
    description:
      "The ID-D1 chassis with a taller three-shelf rack, for lighter parts moved in larger batches. Same safety scanner and the same docking behaviour.",
    buyOff: 440_000,
    stock: [["BKK-WH01", 1, 0]],
    core: {
      dimensions: "900 × 620 × 1,420 mm",
      weight: "134 kg",
      speed: "1.5 m/s",
      climb: "8° (14%)",
      battery: "48 V / 60 Ah lithium",
      runtime: "10 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM, reflector-assisted docking",
      sensors: "Safety laser scanner, 3D LiDAR, depth camera, safety bumper",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE",
      noise: "≤ 60 dB(A)",
      ingress: "IP44",
    },
    extra: [
      ["Rated payload", "80 kg"],
      ["Shelves", "3, adjustable"],
      ["Shelf clearance", "320 mm"],
      ["Safety rating", "PL d / Cat. 3 safety scanner"],
      ["Operating temperature", "0 °C to 45 °C"],
    ],
  },
  {
    slug: "kettybot",
    name: "KettyBot",
    modelId: "KETTY-PRO",
    category: "delivery",
    tagline: "Delivery robot with advertising screen",
    description:
      "Carries orders and runs promotions on an 18.5-inch front panel between rounds. The narrowest body in the delivery range, so it clears a 55 cm gap between tables.",
    buyOff: 160_000,
    reorderPoint: 8,
    stock: [["BKK-WH01", 2, 0]],
    core: {
      dimensions: "460 × 430 × 1,180 mm",
      weight: "38 kg",
      speed: "1.0 m/s",
      climb: "4° (7%)",
      battery: "15 Ah lithium",
      runtime: "12 hours",
      charge: "4 hours",
      navigation: "Visual SLAM with marker assistance",
      sensors: "3D obstacle camera, IR pair, collision bumper",
      connectivity: "Wi-Fi 2.4/5 GHz",
      noise: "≤ 48 dB(A)",
    },
    extra: [
      ["Trays", "3"],
      ["Total payload", "15 kg"],
      ["Minimum passage width", "550 mm"],
      ["Advertising display", "18.5-inch, portrait"],
      ["Content management", "Scheduled playlists via fleet console"],
    ],
  },

  /* ------------------------------ reception ------------------------------ */
  {
    slug: "kettybot-receptionist",
    name: "KettyBot Receptionist",
    modelId: "KETTY-RCP",
    category: "reception",
    tagline: "Greeting and wayfinding robot",
    description:
      "The KettyBot chassis configured for front of house: it greets arrivals, checks them in on the touchscreen and walks them to where they are going.",
    buyOff: 160_000,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "460 × 430 × 1,180 mm",
      weight: "38 kg",
      speed: "1.0 m/s",
      climb: "4° (7%)",
      battery: "15 Ah lithium",
      runtime: "12 hours",
      charge: "4 hours",
      navigation: "Visual SLAM with marker assistance",
      sensors: "3D obstacle camera, face detection camera, IR pair, bumper",
      connectivity: "Wi-Fi 2.4/5 GHz",
      noise: "≤ 48 dB(A)",
    },
    extra: [
      ["Display", "18.5-inch portrait touchscreen"],
      ["Languages", "Thai, English, Chinese, Japanese"],
      ["Greeting trigger", "Face detection up to 3 m"],
      ["Check-in", "QR code, ID scan, staff notification"],
      ["Wayfinding", "Escorts visitor to a mapped destination"],
    ],
  },

  /* -------------------------------- patrol ------------------------------- */
  {
    slug: "blend",
    name: "Blend",
    modelId: "BLEND-P1",
    category: "patrol",
    tagline: "Autonomous security patrol unit",
    description:
      "Walks a fixed route on a schedule, streaming thermal and optical video back to the security desk and raising an alert on anything it does not recognise. Runs the small hours so a guard does not have to.",
    buyOff: 1_600_000,
    reorderPoint: 2,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "680 × 620 × 1,650 mm",
      weight: "145 kg",
      speed: "1.8 m/s",
      climb: "10° (17%)",
      battery: "48 V / 100 Ah lithium",
      runtime: "12 hours",
      charge: "4 hours",
      navigation: "3D LiDAR SLAM with GNSS-assisted outdoor mode",
      sensors: "3D LiDAR, 4K PTZ camera, thermal camera, gas sensor, microphone array",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, 5G option",
      noise: "≤ 55 dB(A)",
      ingress: "IP54",
    },
    extra: [
      ["Optical camera", "4K PTZ, 30× optical zoom"],
      ["Thermal camera", "640 × 512, ±2 °C accuracy"],
      ["Face recognition", "Optional, watch-list matching"],
      ["Licence plate recognition", "Optional"],
      ["Two-way audio", "Yes, speaker and microphone array"],
      ["Alarm output", "Siren, strobe, VMS integration"],
      ["Operating temperature", "-10 °C to 50 °C"],
    ],
  },

  /* ------------------------------- cooking ------------------------------- */
  {
    slug: "robochef-1000g",
    name: "Robochef 1000G",
    modelId: "RC-1000G",
    category: "cooking",
    tagline: "Automated wok station",
    description:
      "Cooks a wok dish end to end from a stored recipe: dispenses oil and seasoning, tosses at the right tempo and plates on a signal. Repeats the same dish identically across shifts.",
    buyOff: 950_000,
    reorderPoint: 3,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "1,100 × 900 × 1,450 mm",
      weight: "260 kg",
      connectivity: "Wi-Fi 2.4/5 GHz, Ethernet",
      noise: "≤ 72 dB(A)",
      ingress: "IPX4 wash-down rated",
    },
    extra: [
      ["Wok capacity", "1,000 g per portion"],
      ["Throughput", "Up to 60 portions per hour"],
      ["Heat source", "Induction, 8 kW"],
      ["Temperature range", "60 °C to 300 °C"],
      ["Recipe storage", "500 recipes on device"],
      ["Seasoning channels", "8 automatic dispensers"],
      ["Cleaning", "Automatic wok rinse between portions"],
      ["Power supply", "380 V three-phase, 10 kW"],
    ],
  },
  {
    slug: "robochef-e40a",
    name: "Robochef E40A",
    modelId: "RC-E40A",
    category: "cooking",
    tagline: "Automated fryer station",
    description:
      "Handles the fryer: lowers baskets, times each product separately, lifts and shakes on schedule, and holds oil at temperature. Removes the most common burn risk in a commercial kitchen.",
    buyOff: 720_000,
    reorderPoint: 3,
    stock: [["BKK-WH01", 0, 0]],
    core: {
      dimensions: "900 × 800 × 1,380 mm",
      weight: "195 kg",
      connectivity: "Wi-Fi 2.4/5 GHz, Ethernet",
      noise: "≤ 68 dB(A)",
      ingress: "IPX4 wash-down rated",
    },
    extra: [
      ["Baskets", "4, independently timed"],
      ["Oil capacity", "40 litres"],
      ["Throughput", "Up to 40 kg per hour"],
      ["Temperature range", "120 °C to 200 °C"],
      ["Oil filtration", "Automatic, per shift"],
      ["Recipe storage", "200 programmes on device"],
      ["Power supply", "380 V three-phase, 18 kW"],
    ],
  },

  /* ---------------------------- canal cleaning --------------------------- */
  {
    slug: "canal-cleaner-c1",
    name: "Canal Cleaner C1",
    modelId: "CC-1",
    category: "canal-cleaning",
    tagline: "Waterway surface collector",
    description:
      "An unmanned craft that sweeps floating waste off canals and ponds and holds it in an onboard basket until a crew empties it at the bank. Runs a mapped route on GNSS.",
    buyOff: 1_450_000,
    reorderPoint: 2,
    stock: [["BKK-WH01", 1, 1]],
    core: {
      dimensions: "2,400 × 1,300 × 900 mm",
      weight: "310 kg",
      speed: "1.5 m/s (2.9 knots)",
      battery: "48 V / 200 Ah lithium",
      runtime: "8 hours",
      charge: "6 hours",
      navigation: "GNSS RTK waypoint routing with obstacle avoidance",
      sensors: "3D LiDAR, RGB camera ×2, sonar, water quality probe",
      connectivity: "4G LTE, 2.4 GHz telemetry link",
      ingress: "IP67 hull",
    },
    extra: [
      ["Collection basket", "300 litres"],
      ["Collection width", "1,200 mm"],
      ["Collection rate", "Up to 200 kg per hour"],
      ["Minimum water depth", "400 mm"],
      ["Water quality logging", "pH, dissolved oxygen, turbidity"],
      ["Hull material", "HDPE, twin pontoon"],
      ["Remote control range", "Up to 1 km line of sight"],
    ],
  },

  /* -------------------------------- spider ------------------------------- */
  {
    slug: "spiderbot-j1",
    name: "SpiderBot J1",
    modelId: "SPD-J1",
    category: "spider",
    tagline: "Facade cleaning robot",
    description:
      "Climbs glass on suction and cleans facades up to 150 metres without a cradle or rope crew. Takes the highest-risk job in building maintenance off people.",
    buyOff: 1_190_000,
    reorderPoint: 2,
    stock: [["BKK-WH01", 0, 1]],
    core: {
      dimensions: "1,050 × 780 × 320 mm",
      weight: "68 kg",
      speed: "0.25 m/s on glass",
      battery: "48 V / 40 Ah lithium",
      runtime: "5 hours",
      charge: "3 hours",
      navigation: "Facade grid mapping with edge detection",
      sensors: "Ultrasonic edge array, IMU, suction pressure sensors, RGB camera",
      connectivity: "Wi-Fi 2.4/5 GHz, 2.4 GHz control link",
      ingress: "IP65",
    },
    extra: [
      ["Maximum working height", "150 m"],
      ["Cleaning width", "900 mm"],
      ["Cleaning rate", "Up to 300 m² per hour"],
      ["Adhesion", "Dual vacuum with mechanical safety tether"],
      ["Safety tether", "Rated 1,200 kg"],
      ["Surface types", "Glass, polished stone, aluminium composite"],
      ["Water supply", "Ground-fed hose, 2 bar minimum"],
    ],
  },
  {
    slug: "spiderbot-k3",
    name: "SpiderBot K3",
    modelId: "SPD-K3",
    category: "spider",
    tagline: "High-rise facade system",
    description:
      "The J1 principle scaled for towers: three coordinated climbing heads working one facade at once, to 300 metres. The flagship of the range and the largest single line item RaasPal quotes.",
    buyOff: 2_700_000,
    reorderPoint: 2,
    stock: [["BKK-WH01", 0, 4]],
    core: {
      dimensions: "1,400 × 980 × 380 mm per head",
      weight: "94 kg per head",
      speed: "0.3 m/s on glass",
      battery: "48 V / 60 Ah lithium per head",
      runtime: "6 hours",
      charge: "3.5 hours",
      navigation: "Facade grid mapping, multi-head coordination",
      sensors: "Ultrasonic edge array, IMU, suction pressure sensors, RGB camera ×2",
      connectivity: "Wi-Fi 2.4/5 GHz, 4G LTE, 2.4 GHz control link",
      ingress: "IP65",
    },
    extra: [
      ["Heads per system", "3, coordinated"],
      ["Maximum working height", "300 m"],
      ["Cleaning width", "1,200 mm per head"],
      ["Cleaning rate", "Up to 900 m² per hour combined"],
      ["Adhesion", "Dual vacuum with mechanical safety tether"],
      ["Safety tether", "Rated 1,500 kg per head"],
      ["Wind rating", "Operates to 12 m/s"],
      ["Water supply", "Ground-fed hose, 3 bar minimum"],
    ],
  },
];

function buildSpecs(seed: SeedRobot): Spec[] {
  const rows: Spec[] = [];
  for (const [key, label] of CORE_ORDER) {
    const value = seed.core[key];
    if (value) rows.push({ label, value });
  }
  for (const [label, value] of seed.extra ?? []) {
    rows.push({ label, value });
  }
  return rows;
}

function buildLocations(seed: SeedRobot): StockByLocation[] {
  return seed.stock.map(([code, onHand, demo]) => ({ code, onHand, demo }));
}

/** Spread the seed timestamps over the last three weeks so the activity feed
 *  and "last updated" columns look like a system that has been in use. */
function seededTimestamp(index: number, now: number): string {
  const hoursBack = 6 + ((index * 37) % 480);
  return new Date(now - hoursBack * 3_600_000).toISOString();
}

const SEED_EDITORS = [
  "Sai Kham",
  "Nattapong S.",
  "Pimchanok R.",
  "Somchai T.",
  "Warisara K.",
];

export function seedRobots(now = Date.now()): Robot[] {
  return SEED.map((seed, index) => ({
    slug: seed.slug,
    name: seed.name,
    modelId: seed.modelId,
    category: seed.category,
    tagline: seed.tagline,
    description: seed.description,
    lifecycle: "active" as const,
    buyOff: seed.buyOff,
    reserved: seed.reserved ?? 0,
    reorderPoint: seed.reorderPoint ?? 5,
    locations: buildLocations(seed),
    lease: leaseSchedule(seed.buyOff),
    maintenance: maintenanceSchedule(seed.buyOff),
    specs: buildSpecs(seed),
    image: null,
    brochure: null,
    updatedAt: seededTimestamp(index, now),
    updatedBy: SEED_EDITORS[index % SEED_EDITORS.length],
  }));
}
